### ISSUE TITLE
Translations to be complete

### ISSUE THREAD

**Issue by JDJGInc** [JDJG-Holding-Team/Connie-Melody-Skye#28]
```yaml
brazil_portuguese : pt-BR
bulgarian : bg
chinese : zh-CN
croatian : hr
danish : da
dutch : nl
finnish : fi
french : fr
greek : el
hungarian : hu
indonesian : id
lithuanian : lt
romanian : ro
russian : ru
taiwan_chinese : zh-TW
thai : th
ukrainian : uk
```

Complete:
```yaml
american_english : en-US
british_english : en-GB
czech : cs
german : de
hindi : hi
italian : it
japanese : ja
korean : ko
latin_american_spanish : es-419
norwegian : no
polish : pl
spain_spanish : es-ES
swedish : sv-SE
turkish : tr
vietnamese : vi
```
